name: main checks

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: HTML5 Validator
        # You may pin to the exact commit or the version.
        # uses: Cyb3r-Jak3/html5validator-action@41633d488eb36e18fd1a95ffc83daf1bf22a75bd
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          # Path of the files to test
          root: /
          # Path of config file

          # Format for logging output. Valid values: gnu, xml, json, text
          format: text # optional
          # Logging Level. Valid values: DEBUG, INFO, WARNING. Default: WARNING
          log_level: WARNING # optional, default is WARNING
          # Checks css as well
          css: true
          # Files or directories to ignore in checking
          blacklist: /.github/workflows
          # Skip checking that code has been checked out
